### ISSUE TITLE
Incorrect Assignment of ReloadlySDKClientId and ReloadlySDKSecretId in ReloadlyAuthentication.shared.configure()

### ISSUE THREAD

**Issue by mhlangagc** [Reloadly/reloadly-sdk-ios#10]
The Authentication configuration function `ReloadlyAuthentication.shared.configure()` incorrectly assigns the `ReloadlySDKClientId` and `ReloadlySDKSecretId`

## Describe the bug
In the `ReloadlyAuthentication.shared.configure()` the following function is found in the `ReloadlyAuthentication` class under `configure` function:

```
self.clientId = clientId ?? (dictionary?["ReloadlySDKSecretId"] as? String) ?? ""
self.clientSecret = clientSecret ?? (dictionary?["ReloadlySDKClientId"] as? String) ?? ""
``` 
As shown, the `ReloadlySDKSecretId` value fetched from the info.plist is assigned to the `clientId` instead of the `clientSecret` while the `ReloadlySDKClientId` value fetched from the info.plist is assigned to the `clientSecret`. 

## Expected Behavior
This part of the code should be written in this way, where the correct assignments are done:
```
self.clientId = clientId ?? (dictionary?["ReloadlySDKClientId"] as? String) ?? ""
self.clientSecret = clientSecret ?? (dictionary?["ReloadlySDKSecretId"] as? String) ?? ""
``` 

## File Reference
https://github.com/Reloadly/reloadly-sdk-ios/blob/2c7577452e879b21f890f92474829e975c889535/ReloadlySDK/Classes/ReloadlyAuthentication/ReloadlyAuthentication.swift#L61

## Context
SDK authentication call fails unless this is reversed.

**Comment by epiard13** [comment]
@mhlangagc Thank you for reporting this, we are working to address it quickly.
