### ISSUE TITLE
Externalize Client ID and Client Secret in Plist

### ISSUE THREAD

**Issue by arunkpatra** [Reloadly/reloadly-sdk-ios#5]
## Describe the Feature

Allow client ID and client secret to be specified as property list file, e.g. Reloadly-Info.plist.
<img width="1010" alt="Screen Shot 2021-05-22 at 4 47 53 PM" src="https://user-images.githubusercontent.com/2806069/119224782-baf50e80-bb1d-11eb-9105-9f63e7bc1e32.png">

Then the initilization logic could be simplified to:

```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        ReloadlyAuthentication.shared.configure()
        return true
    }
}
```

## Is your Feature Request related to a problem?
No.

## Proposed Solution
Internal code, would look for a client supplied property list file named `Reloadly-Info.plist` in client app. It would read the properties for client ID, Client secret and environment type (e.g. Sandbox) and initialize the API accordingly.  This allows customer code to not hardcode the client ID and secret and keep it in a plist instead. Its upto the customer to employ a suitable method to automate picking up a production Plist file during release build.

## Describe alternatives you've considered
Current approach is OK.

## Additional Context
I would like to avoid hard coding secrets.

- [ ] I may be able to implement this feature request

## Your Environment

* Reloadly iOS SDK version used: latest
* Operating System and version: iOS 14.5.1

**Comment by epiard13** [comment]
@arunkpatra Thanks for submitting 👍   we'll update.

**Comment by markevychtaras** [comment]
@epiard13 PR Added
